version: '3.4'

services:
  sql_server2022:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "S3cur3P@ssW0rd!"
        ACCEPT_EULA: "Y"
    # --- to persit data in volume
    # volumes:
    #  - C:/Work/Databases/TournamentDb:/var/opt/mssql/data
    
  tournamentapi:
    image: ${DOCKER_REGISTRY-}tournamentwebapi
    build:
      context: .
      dockerfile: TournamentApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5062:80"
    # volumes:
    #   - "./TournamentData/tournament.db:/TournamentData/tournament.db"
    depends_on:
      - sql_server2022


  webapp:
    image: ${DOCKER_REGISTRY-}tournamentwebapp:v1
    build:
      context: ../TournamentAppNG
      dockerfile: Dockerfile
    ports:
      - "4200:80"