version: '3.4'

services:
  tournamentapi:
    image: ${DOCKER_REGISTRY-}tournamentwebapi
    build:
      context: .
      dockerfile: TournamentApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5062:80"
    volumes:
      - "./TournamentData/tournament.db:/TournamentData/tournament.db"
  webapp:
    image: ${DOCKER_REGISTRY-}tournamantwebapp:v1
    build:
      context: ../TournamentAppNG
      dockerfile: Dockerfile
    ports:
      - "4200:80"


